<?php
// $Id$
 
/**
 * Implementation of hook_install().
 */
function iform_ajaxproxy_install() {
}

/**
 * Implementation of hook_uninstall().
 */
function iform_ajaxproxy_uninstall() {
  // Get module variables
  $results = db_query("SELECT v.name FROM {variable} AS v WHERE v.name LIKE '%s%%'", 'iform_ajaxproxy_');
  // Remove variables
  while ($row = db_fetch_array($results)) {
    variable_del($row['name']);
  }
}
