<?php
/**
 * Implements hook_variable_info().
 *
 * Returns information about the variables used by this module, allowing an
 * admin interface to be created. We use a single radio group to decide if we
 * use the custom, minimised or full debug version of the OpenLayers.js file.
 */
function iform_licences_variable_info($options) {
  $variable['iform_licences_mode'] = array(
    'title' => t('Indicia licence choices'),
    'description' => t('Option to apply user licence choice for records and/or media separately.'),
    'type' => 'radios',
    'options' => array(
      'records' => t('User can select licence for records only'),
      'media' => t('User can select licence for media (photos etc) only'),
      'records+media' => t('User can select licence for records and media separately'),
    ),
    'default' => 'media',
    'addToIndiciaSettingsPage' => TRUE,
  );
  return $variable;
}

function iform_licences_form_alter(&$form, &$form_state, $form_id) {
  iform_load_helpers(array('data_entry_helper'));
  if (($form_id === 'user_profile_form' || $form_id === 'user_register_form')) {
    $conn = iform_get_connection_details(NULL);
    $readAuth = data_entry_helper::get_read_auth($conn['website_id'], $conn['password']);
    $licences = data_entry_helper::get_population_data([
      'table' => 'licence',
      'extraParams' => $readAuth,
    ]);
    $licencesApplyTo = explode('+', variable_get('iform_licences_mode', 'media'));
    if (count($licences)) {
      $indiciaUserId = hostsite_get_user_field('indicia_user_id');
      $currentLicenceId = NULL;
      $currentMediaLicenceId = NULL;
      if ($indiciaUserId) {
        $current = data_entry_helper::get_population_data(array(
          'table' => 'users_website',
          'extraParams' => $readAuth + array(
            'user_id' => $indiciaUserId,
            'columns' => 'licence_id,media_licence_id',
          ),
          'caching' => FALSE,
        ));
        $currentLicenceId = $current[0]['licence_id'];
        $currentMediaLicenceId = $current[0]['media_licence_id'];
      }
      $options = [];
      foreach ($licences as $licence) {
        $options[$licence['id']] = "$licence[code]: <a href='$licence[url_readable]'>$licence[title]</a>";
      }
      foreach ($licencesApplyTo as $licenceFor) {
        $label = $licenceFor === 'records' ? t('records') : t('photos and other media');
        $thisLicenceId = $licenceFor === 'records' ? $currentLicenceId : $currentMediaLicenceId;
        $description = t('Select the licence to apply to your @label.', ['@label' => $label]) . ' ';
        // For media only, add some text to recommend CC0 and avoiding commercially valuable images
        $description .= $licenceFor === 'records' ? '' : t('<b>If you are happy to select a CC0 or CC BY licence option, that will provide the best chance for your photos to be used in research and conservation.</b> ');

        if ($form_id === 'user_profile_form') {
          // Extra warning shown when changing existing setting.
          if ($thisLicenceId) {
            $description .= t(
              'If you change the selected licence then it will only affect @label you enter from now on.',
              ['@label' => $licenceFor]
            );
          }
          else {
            $description .= strtoupper(
              t('This licence will also be applied to all the @label you have previously uploaded to @site.',
              [
                '@label' => $label,
                '@site' => variable_get('site_name', 'this system'),
              ]
            ));
          }
        }
        $form["field_iform_licence_$licenceFor"] = array(
          '#type' => 'radios',
          '#title' => t('<span id="licenceopts">Licence for your @label</span>', ['@label' => $label]),
          '#options' => $options,
          '#description' => $description,
          '#required' => TRUE,
          '#default_value' => $thisLicenceId,
        );
      }
      $form['#submit'][] = 'iform_licences_form_submit';
    }
  }
}

function iform_licences_form_submit($form, &$form_state) {
  $conn = iform_get_connection_details(NULL);
  $auth = data_entry_helper::get_read_write_auth($conn['website_id'], $conn['password']);
  $indiciaUserId = hostsite_get_user_field('indicia_user_id');
  $existingUsersWebsiteId = NULL;
  if ($indiciaUserId) {
    $current = data_entry_helper::get_population_data(array(
      'table' => 'users_website',
      'extraParams' => $auth['read'] + array(
        'user_id' => $indiciaUserId,
        'columns' => 'id,licence_id,media_licence_id',
      ),
      'caching' => FALSE
    ));
    $values = [];
    if (count($current)) {
      $currentUw = $current[0];
      $values['id'] = $currentUw['id'];
    }
    else {
      $currentUw = [
        'licence_id' => NULL,
        'media_licence_id' => NULL,
      ];
      $values = [
        'user_id' => $indiciaUserId,
        'website_id' => variable_get('indicia_website_id', ''),
      ];
    }
    $change = FALSE;
    if (!empty($form_state['values']['field_iform_licence_records']) &&
        $form_state['values']['field_iform_licence_records'] !== $currentUw['licence_id']) {
      $values['licence_id'] = $form_state['values']['field_iform_licence_records'];
      $change = TRUE;
    }
    if (!empty($form_state['values']['field_iform_licence_media']) &&
        $form_state['values']['field_iform_licence_media'] !== $currentUw['media_licence_id']) {
      $values['media_licence_id'] = $form_state['values']['field_iform_licence_media'];
      $change = TRUE;
    }
    if ($change) {
      $s = data_entry_helper::build_submission($values, array('model' => 'users_website'));
      $r = data_entry_helper::forward_post_to('users_website', $s, $auth['write_tokens']);
      if (!isset($r['success'])) {
        watchdog('iform', 'Error occurred when saving a user licence: ' . var_export($r, TRUE));
        drupal_set_message(var_export($r, TRUE), 'error');
      }
    }
    else {
      drupal_set_message('no change');
    }
  }

}

function iform_licences_user_login (&$edit, $account) {

  global $user;
  if (user_is_logged_in()) {
    iform_load_helpers(array('data_entry_helper'));
    $readAuth=data_entry_helper::get_read_auth(variable_get('indicia_website_id',''), variable_get('indicia_password',''));
    $indiciaUserId = $account->field_indicia_user_id[LANGUAGE_NONE]['0']['value'];
    $current = data_entry_helper::get_population_data(array(
      'table' => 'users_website',
      'extraParams' => $readAuth + array(
          'user_id' => $indiciaUserId,
          'columns' => 'media_licence_id'
        ),
      'caching' => FALSE,
    ));
    $currentMediaLicenceId = $current[0]['media_licence_id'];
    if (!isset($currentMediaLicenceId)) {
      $link = url('user/' . $user->uid . '/edit', ['fragment' => 'licenceopts']);
      drupal_set_message(t('You have not yet specified a media licence. This limits the usefulness of your images. <a href="@link">To set a licence, edit your profile page, and select an option.</a>', ['@link' => $link]));
    }
  }
}
